# Generated by Django 6.1.1 on 2026-09-15 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps_data', models.JSONField()),
                ('current_step', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_params', models.JSONField()),
                ('activation_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.activationcode')),
            ],
        ),
    ]
